services:
  - type: web
    name: timelya-web
    plan: starter
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hecmdb
          property: connectionString
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          name: timelya-web
          property: host

databases:
  - name: hecm-db
    plan: free
    region: frankfurt
