# Generated by Django 5.1.1 on 2025-03-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Rejeté')], default='pending', max_length=10, verbose_name='Statut de la réponse')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Réponse de disponibilité',
                'verbose_name_plural': 'Réponses de disponibilités',
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date de début de la disponibilité', verbose_name='Date de début')),
                ('end_date', models.DateField(help_text='Date de fin de la disponibilité', verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('filieres', models.ManyToManyField(related_name='availability_requests', to='courses.departmentlevel', verbose_name='Filières')),
            ],
            options={
                'verbose_name': 'Demande de disponibilité',
                'verbose_name_plural': 'Demandes de disponibilités',
                'permissions': [('can_send_availability_request', 'Peut envoyer une demande de disponibilité')],
            },
        ),
    ]
