# Generated by Django 5.1.1 on 2025-01-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityrequest',
            name='teachers',
            field=models.ManyToManyField(help_text='Enseignants sélectionnés pour cette demande', related_name='availability_requests', to='users.teacherprofile', verbose_name='Enseignants'),
        ),
        migrations.AddField(
            model_name='availabilityresponse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='availability.availabilityrequest', verbose_name='Demande'),
        ),
        migrations.AddField(
            model_name='availabilityresponse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_responses', to='users.teacherprofile', verbose_name='Enseignant'),
        ),
        migrations.AlterUniqueTogether(
            name='availabilityresponse',
            unique_together={('request', 'teacher')},
        ),
    ]
