# Generated by Django 5.1.1 on 2025-03-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityrequest',
            options={'permissions': [('can_send_availabilityrequest', 'Peut envoyer une demande de disponibilité'), ('can_view_availabilityrequest_history', "Peut voir l'historique des demande de disponibilité"), ('can_view_availabilityrequest_pending', 'Peut voir les demande de disponibilité en attente')], 'verbose_name': 'Demande de disponibilité', 'verbose_name_plural': 'Demandes de disponibilités'},
        ),
    ]
