# Generated by Django 5.1.1 on 2025-02-21 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('rooms', '0003_alter_room_room_number'),
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Label généré automatiquement, ex : '08:00 - 10:00'.", max_length=50)),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['start_time'],
                'unique_together': {('start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('department_levels', models.ManyToManyField(related_name='timetables', to='courses.departmentlevel', verbose_name='Départements - Niveaux')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du cours')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='rooms.room', verbose_name='Salle')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='subjects.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='users.teacherprofile', verbose_name='Enseignant')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='timetable.timeslot', verbose_name='Créneau horaire')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='timetable.timetable', verbose_name='Emploi du temps')),
            ],
            options={
                'verbose_name': 'Session de cours',
                'verbose_name_plural': 'Sessions de cours',
                'ordering': ['date', 'timeslot__start_time'],
            },
        ),
    ]
