# Generated by Django 5.1.1 on 2025-03-09 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('timetable', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='users.teacherprofile', verbose_name='Enseignant'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='coursesession',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='timetable.timeslot', verbose_name='Créneau horaire'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='department_levels',
            field=models.ManyToManyField(related_name='timetables', to='courses.departmentlevel', verbose_name='Départements - Niveaux'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='timetable.timetable', verbose_name='Emploi du temps'),
        ),
    ]
