# Generated by Django 5.1.7 on 2025-03-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['start_date'], 'permissions': [('config_recap_semaine', "Peut configurer et imprimer le recapitulatif de l'emplois du temps et la repartition des salles de la semaine")], 'verbose_name': 'Emploi du temps', 'verbose_name_plural': 'Emplois du temps'},
        ),
    ]
