# Generated by Django 5.1.7 on 2025-04-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['start_date'], 'permissions': [('config_recap_semaine', "Peut configurer et imprimer le recapitulatif de l'emplois du temps et la repartition des salles de la semaine"), ('view_timetable_recap', "Peut voir le recapitulatif de l'emplois du temps et la repartition des salles de la semaine")], 'verbose_name': 'Emploi du temps', 'verbose_name_plural': 'Emplois du temps'},
        ),
    ]
