# Generated by Django 5.1.7 on 2025-04-26 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_coursesession_options_alter_timetable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['period__start_date'], 'permissions': [('config_recap_semaine', "Peut configurer et imprimer le récapitulatif de l'emploi du temps et la répartition des salles de la semaine")], 'verbose_name': 'Emploi du temps', 'verbose_name_plural': 'Emplois du temps'},
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_date',
        ),
        migrations.AddField(
            model_name='timetable',
            name='year',
            field=models.PositiveIntegerField(default=2025, verbose_name='Année'),
        ),
        migrations.CreateModel(
            name='SchedulePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Ex : Trimestre 1, Semestre 2, etc.', max_length=100, null=True, verbose_name='Nom de la période')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'Période de planification',
                'verbose_name_plural': 'Périodes de planification',
                'ordering': ['start_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.AddField(
            model_name='timetable',
            name='period',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='timetable.scheduleperiod', verbose_name='Période de planification'),
            preserve_default=False,
        ),
    ]
