# Generated by Django 5.1.1 on 2025-01-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2, unique=True, verbose_name='Niveau')),
            ],
            options={
                'verbose_name': "Niveau d'études",
                'verbose_name_plural': "Niveaux d'études",
            },
        ),
        migrations.CreateModel(
            name='DepartmentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_levels', to='courses.department', verbose_name='Département')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_levels', to='courses.level', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Niveau départemental',
                'verbose_name_plural': 'Niveaux départementaux',
                'unique_together': {('department', 'level')},
            },
        ),
    ]
