# Generated by Django 5.1.1 on 2025-09-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notification_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
