# Generated by Django 5.1.1 on 2025-01-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentLevelSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_levels_subjects', to='courses.departmentlevel', verbose_name='Niveau Départemental')),
            ],
            options={
                'verbose_name': 'Matière par département et niveau',
                'verbose_name_plural': 'Matières par département et niveau',
            },
        ),
    ]
