# Generated by Django 5.1.1 on 2025-03-09 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentlevelsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_levels_subjects', to='subjects.subject', verbose_name='Matière'),
        ),
        migrations.AddConstraint(
            model_name='departmentlevelsubject',
            constraint=models.UniqueConstraint(fields=('department_level', 'subject'), name='unique_departmentlevel_subject'),
        ),
    ]
