# Generated by Django 5.1.1 on 2025-01-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentlevelsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_levels_subjects', to='subjects.subject', verbose_name='Matière'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentlevelsubject',
            unique_together={('department_level', 'subject')},
        ),
    ]
