# Generated by Django 5.1.1 on 2024-12-20 23:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin_general', 'Administrateur Général'), ('admin_exams', 'Administrateur des Examens')], default='admin_general', max_length=50, verbose_name='Type d’administrateur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('role', models.CharField(choices=[('student', 'Étudiant'), ('teacher', 'Enseignant'), ('parent', 'Parent'), ('admin', 'Administrateur')], max_length=20, verbose_name='Rôle')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone non valide.', regex='^(?:\\+229|00229|\\d{10})[\\s-]?(\\d{2,})[\\s-]?(\\d{2,})[\\s-]?(\\d{2,})[\\s-]?(\\d{2,})[\\s-]?(\\d{2,})$')], verbose_name='Numéro de téléphone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('profile_picture', models.ImageField(blank=True, db_index=True, null=True, upload_to='profile_pictures/', verbose_name='Photo de profil')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date d’inscription')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernier login')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('none', 'Aucun')], default='email', max_length=20, verbose_name='Méthode de contact préférée')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Masculin'), ('female', 'Féminin'), ('other', 'Autre')], max_length=10, null=True, verbose_name='Genre')),
                ('password_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de mise à jour du mot de passe')),
                ('first_login', models.BooleanField(default=True, verbose_name='Première connexion')),
                ('password_changed', models.BooleanField(default=False, verbose_name='Mot de passe modifié')),
                ('reset_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Code de réinitialisation')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group', verbose_name='Groupes')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission', verbose_name='Permissions utilisateur')),
            ],
            options={
                'verbose_name': 'Utilisateur personnalisé',
                'verbose_name_plural': 'Utilisateurs personnalisés',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managed_departments', models.TextField(blank=True, verbose_name='Départements gérés')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('admin_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='users.admintype', verbose_name='Type d’admin')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='ID étudiant')),
                ('enrollment_status', models.CharField(choices=[('active', 'Actif'), ('graduated', 'Diplômé'), ('withdrawn', 'Désinscrit')], default='active', max_length=20, verbose_name='Statut d’inscription')),
                ('is_class_representative', models.BooleanField(default=False, verbose_name='Représentant de classe')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.departmentlevel', verbose_name='Fillière d’étude')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Étudiant',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('children', models.ManyToManyField(related_name='parents', to='users.studentprofile', verbose_name='Enfants')),
            ],
            options={
                'verbose_name': 'Profil Parent',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Grade')),
                ('department_levels', models.ManyToManyField(related_name='teachers', to='courses.departmentlevel', verbose_name='Niveaux départementaux')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='subjects.subject', verbose_name='Matières')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Enseignant',
                'ordering': ['user__last_name'],
            },
        ),
    ]
