# Generated by Django 5.1.1 on 2025-01-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='managed_departments',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_login_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de première connexion'),
        ),
    ]
