# Generated by Django 5.1.1 on 2025-03-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'permissions': [('view_profile', 'Peut voir son profil'), ('change_profile', 'Peut modifier son profil')], 'verbose_name': 'Utilisateur personnalisé', 'verbose_name_plural': 'Utilisateurs personnalisés'},
        ),
    ]
