# Generated by Django 5.1.1 on 2025-07-13 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Utilisateur personnalisé', 'verbose_name_plural': 'Utilisateurs personnalisés'},
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='managed_departments',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_contact_method',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_class_representative',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Numéro invalide. Format accepté : 8 ou 10 chiffres ex : 97011234,97 01 12 34 ou 01 97 01 12 34', regex='^(\\d{8}|\\d{10}|(\\d{2}( \\d{2}){3})|(\\d{2}( \\d{2}){4}))$')], verbose_name='Numéro de téléphone'),
        ),
    ]
