# Generated by Django 5.1.1 on 2025-07-13 12:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_level_name'),
        ('users', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code OTP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_code_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration OTP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_code_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration du code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Numéro invalide. Format accepté : 8 ou 10 chiffres ex : 97011234,97 01 12 34 ou 01 97 01 12 34', regex='^(\\d{8}|\\d{10}|(\\d{2}( \\d{2}){3})|(\\d{2}( \\d{2}){4}))$')], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.departmentlevel', verbose_name='Filière d’étude'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID étudiant'),
        ),
    ]
