# Generated by Django 5.1.1 on 2025-07-14 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_otp_code_customuser_otp_code_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date d’archivage'),
        ),
        migrations.CreateModel(
            name='StudentArchiveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('archived', 'Archivé'), ('unarchived', 'Désarchivé')], max_length=10)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_history', to='users.studentprofile')),
            ],
        ),
    ]
