# Generated by Django 5.1.1 on 2025-07-17 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_level_name'),
        ('users', '0005_studentprofile_archived_studentprofile_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Numéro invalide. Format attendu : +22997011234 ou 97011234', regex='^(\\+229\\d{8}|\\d{8})$')], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.departmentlevel', verbose_name='Filière d’étude'),
        ),
    ]
