# Generated by Django 5.1.1 on 2025-07-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentarchivehistory',
            options={'verbose_name': 'Profil Parent'},
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='relation',
            field=models.CharField(choices=[('father', 'Père'), ('mother', 'Mère'), ('guardian', 'Tuteur')], default='guardian', max_length=10, verbose_name='Lien avec l’enfant'),
        ),
    ]
