# Generated by Django 5.1.1 on 2025-07-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_parentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentprofile',
            options={'verbose_name': 'Profil Parent'},
        ),
        migrations.AlterModelOptions(
            name='studentarchivehistory',
            options={},
        ),
    ]
