# Generated by Django 5.1.1 on 2025-08-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_parentprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_code_expiry',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code OTP'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='otp_code_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration OTP'),
        ),
    ]
