# Generated by Django 5.1.1 on 2025-08-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Code de réinitialisation'),
        ),
    ]
