# Generated by Django 5.1.1 on 2025-09-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_reset_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('student', 'Étudiant'), ('teacher', 'Enseignant'), ('parent', 'Parent'), ('admin', 'Administrateur')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ManyToManyField(to='users.role', verbose_name='Rôle'),
        ),
    ]
