# Generated by Django 5.1.1 on 2025-08-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Code de la matière'),
            preserve_default=False,
        ),
    ]
