# Generated by Django 5.1.1 on 2025-02-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.PositiveIntegerField(max_length=20, unique=True, verbose_name='Numéro de la salle'),
        ),
    ]
