# Generated by Django 5.1.1 on 2024-12-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(default='', max_length=255, verbose_name='Emplacement'),
            preserve_default=False,
        ),
    ]
