# Generated by Django 5.1.1 on 2025-02-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Numéro de la salle'),
        ),
    ]
