# Generated by Django 5.1.1 on 2024-12-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_capacity_room_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['created_at', 'reservation_date', 'start_time'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='equipment_needed',
        ),
        migrations.AddField(
            model_name='reservation',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Validée'),
        ),
    ]
